services:
  mc2:
    services:
  cobbleverse-server:
    image: itzg/minecraft-server:latest
    ports:
      - "25568:25568"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/cobbleverse-cobblemon"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      CF_MODPACK_ZIP: /modpacks/Cobbleverse.zip
      CF_FORCE_SYNCHRONIZE: "true"
      MEMORY: "4096M"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_FLIGHT: "true"
      MAX_PLAYERS: "10"
    volumes:
      - ./data:/data
      - ./modpacks:/modpacks
    volumes:
      - ./data:/data
      - ./Cobbleverse.zip:/modpacks/Cobbleverse.zip:ro
