services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: modpack-mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.19.2"  # or remove if letting CurseForge decide
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/ciscos-adventure-rpg-ultimate"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      MEMORY: 10G
    volumes:
      - ./data:/data
    network_mode: "bridge"
    cpus: 4.0
