services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: modpack-mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      CF_SLUG: ciscos-adventure-rpg-ultimate
      CF_FILE_ID: "6371971"
      MEMORY: 10G
    volumes:
      - ./data:/data
    network_mode: "bridge"
    cpus: 4.0
