services:
  mc:
    image: itzg/minecraft-server:java8-jdk
    container_name: modpack-mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.16.5"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      MEMORY: 10G
      JVM_OPTS: "-Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxGCPauseMillis=50 -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:G1HeapRegionSize=8M -XX:+DisableExplicitGC"
    volumes:
      - ./data:/data
    network_mode: "bridge"
    cpus: 4.0  # <-- This is the correct way to limit to 4 CPUs
