environment:
  EULA: "TRUE"
  TYPE: "AUTO_CURSEFORGE"
  CF_SLUG: "craftoria"
  CF_API_KEY: "$$2a$$10$$61vnjF/HZPsqUdH7tGZ5y.srFvarGH.dRhhFSEctrcsGXRFIixOBi"
  MEMORY: "20480M"
  MAX_PLAYERS: "10"
  USE_AIKAR_FLAGS: "true"
  PLAYER_IDLE_TIMEOUT: "30"
  FORCE_GAMEMODE: "true"
  ENABLE_COMMAND_BLOCK: "true"
  SEED: "-561697773542121824"
  OPS: |-
    7acf6031-37a2-418e-b467-5a75da10bd0b
  ALLOW_FLIGHT: "true"
  
