services:
  mc:
    image: itzg/minecraft-server:java8
    container_name: modpack-mc
    tty: true
    stdin_open: true
    expose:
      - "25565"  # Expose internally only to other containers
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.16.5"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      MEMORY: "8192M"
      MAX_PLAYERS: "10"
    volumes:
      - ./data:/data
    networks:
      - mcnet

  infrared:
    image: haveachin/infrared
    container_name: infrared
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"  # Only expose Infrared to host
    volumes:
      - ../infrared:/proxies
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      INFRARED_CONFIG_PATH: "/proxies"
    networks:
      - mcnet

networks:
  mcnet:
    driver: bridge
