version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: curseforge-server
    ports:
      - "25566:25565"  # External port 25566 mapped to internal Minecraft port 25565
    environment:
      EULA: ${EULA}  # Will read from the .env file
      TYPE: "AUTO_CURSEFORGE"  # Use Auto CurseForge to load modpack
      CF_SLUG: ${CF_SLUG}  # Referencing the modpack slug from .env
      CF_FILENAME_MATCHER: ${CF_FILENAME_MATCHER}  # Use latest or a specific version (optional)
      MEMORY: ${MEMORY}  # Set the memory allocation
      CF_API_KEY: ${CF_API_KEY}  # CurseForge API key
    volumes:
      - ./data:/data  # Mounts data folder to persist Minecraft world data
    networks:
      - mcnet

  infrared:
    image: haveachin/infrared
    container_name: infrared
    ports:
      - "25565:25565"  # External port 25565 for the Infrared proxy
    volumes:
      - ./infrared:/config  # Mounts Infrared config directory
    command: ["infrared", "proxy", "--config", "/config"]  # Starts Infrared with the config mounted
    networks:
      - mcnet

networks:
  mcnet:
    driver: bridge  # Create a bridge network for the services to communicate
