services:
  mc2:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25567:25567"
    environment:
      SERVER_PORT: "25567"
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/bcg"
      CF_API_KEY: "$$2a$$10$$bA6.2mGmk606PaYspFY6juhUcvFwc78AyRCEpcGuV4wgPcpJWkEPO"
      CF_FORCE_SYNCHRONIZE: "true"
      NO_UPDATE: "true"
      MEMORY: "10240M"
      MAX_PLAYERS: "10"
      USE_AIKAR_FLAGS: "true"
      FORCE_GAMEMODE: "true"
      ENABLE_COMMAND_BLOCK: "true"
      SEED: "-561697773542121824"
      OPS: |-
        7acf6031-37a2-418e-b467-5a75da10bd0b
      PLAYER_IDLE_TIMEOUT: "10"
      ALLOW_FLIGHT: "true"
    volumes:
      - "./data:/data"
